model:
  path: "deepseek-ai/Janus-1.3B"
  dtype: "bfloat16"
  device: "cuda"
  
cd_beta: 1.0
parallel_size: 16
pag_scale: 0.0
add: true
cfg_scale: 3.0
image_token_num_per_image: 576
img_size: 384
patch_size: 16

seed: 12
prompt: "prompts.txt"
layer_types: "late"

wandb:
  project: Janus
  entity: 
  sweep_name: "Janus-1.3B"
  sweep_id: null