hydra:
  run:
    dir: .
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - benchmark=geneval
    - model_params=janus
  job:
    name: evaluate
    chdir: null
    override_dirname: benchmark=geneval,model_params=janus
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/server08/yoonjeon_workspace/MMAR/Janus
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/server08/yoonjeon_workspace/MMAR/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      sampling_strategy: cfg
      model_params: janus
      benchmark: geneval
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
benchmark:
  name: geneval
  outdirs: ${home_dir}/geneval/outputs/
  prompts: ${home_dir}/geneval/prompt/evaluation_metadata.jsonl
  batch: 4
  save_as: folder
  model-path: ${home_dir}/geneval/obj_detector/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.pth
model_params:
  model_name: Janus
  cfg_scale: 3.0
  model:
    path: deepseek-ai/Janus-1.3B
    dtype: bfloat16
    device: cuda
  image_token_num_per_image: 576
  img_size: 384
  patch_size: 16
sampling_strategy:
  sample: cfg
  cfg_scale: 4.5
seed: 42
home_dir: /home/server08/hdd1/yoonjeon_workspace/eval/
sample: ${sampling_strategy.sample}
cd_alpha: 0.1
cd_beta: 1.0
expert_scale: 4.5
amateur_scale: 4.5
pag_scale: 0.1
cfg_scale: 4.5
layer_types: all
dynamic_scale: linear
wandb:
  entity: jeoni
  resume: auto
  project: HART
  sweep_name: hart-1024px
