# wandb sweep sweep.yaml
program: sample.py
method: grid  # or bayes, random
parameters:
  pag_scale:
    values: [0.0]
  cfg:
    values: [3.0, 4.0, 5.0]
  layer_types: 
    values: ["all"]
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}